name: crash1

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Crash1
      run:  gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 Part2/crash1.gft
   
