name: 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: crash1Fix
      run: gcc -o giftcardreader Part2/giftcardreaderfixed.c && ./giftcardreader 1 Part2/crash1.gft
    
