name: crash2

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Crash2
      run: gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 Part2/crash2.gft
    
