name: crash2Fixed

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: crash2Fixed
      run: gcc -o giftcardreader Part2/giftcardreaderfixed.c && ./giftcardreader 1 Part2/crash2.gft
    
