name: fuzzer2Fixed

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: fuzzer2Fixed
      run: gcc -o giftcardreader Part3/giftcardreaderfixed.c && ./giftcardreader 1 Part3/fuzzer2.gft
    
