name: fuzzer1

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: fuzzer1
      run: gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 Part3/fuzzer1.gft	
   
