name: hang

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Hang
      run: gcc -o giftcardreader giftcardreader.c && timeout 30s ./giftcardreader 1 Part2/hang.gft
    
